import Header from 'components/layout/Header'
import Head from 'next/head'
import dummyLinks from 'public/api/Menu.json'
import React from 'react'
type LayoutType = {
    children: React.ReactNode
}

const Layout: React.FC<LayoutType> = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header links={dummyLinks} />
            {children}
        </div>
    )
}

export default Layout
